name: build
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: zulu@1.16

      - name: Set up Ruby 2.7 (for microsite)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3

      - name: Install microsite dependencies
        run: bundle install --system --gemfile=src/main/g8/site/Gemfile

      - name: Test
        run: sbt test
